version: '2.1'

services:
  eureka:
    build: eureka-server
    restart: always
    ports:
      - "9091:9091"

  zuul:
    build: zuul
    restart: always
    ports:
      - "9092:9092"
   

  ms_negativacao:
    build: ms_negativacao
    restart: always
    ports:
      - "9093:9093"